use kalamdb_commons::datatypes::KalamDataType;
use kalamdb_commons::schemas::{
    ColumnDefault, ColumnDefinition, TableDefinition, TableOptions, TableType,
};
use kalamdb_commons::{NamespaceId, TableName};

/// Create TableDefinition for system.jobs table
///
/// Schema:
/// - job_id TEXT PRIMARY KEY
/// - job_type TEXT NOT NULL
/// - status TEXT NOT NULL
/// - created_at TIMESTAMP NOT NULL
/// - started_at TIMESTAMP
/// - completed_at TIMESTAMP
/// - error_message TEXT
pub fn jobs_table_definition() -> TableDefinition {
    let columns = vec![
        ColumnDefinition::new(
            1,
            "job_id",
            1,
            KalamDataType::Text,
            false,
            true,
            false,
            ColumnDefault::None,
            Some("Job identifier (UUID)".to_string()),
        ),
        ColumnDefinition::new(
            2,
            "job_type",
            2,
            KalamDataType::Text,
            false,
            false,
            false,
            ColumnDefault::None,
            Some("Job type: flush, retention, cleanup, etc.".to_string()),
        ),
        ColumnDefinition::new(
            3,
            "namespace_id",
            3,
            KalamDataType::Text,
            false,
            false,
            false,
            ColumnDefault::None,
            Some("Namespace ID".to_string()),
        ),
        ColumnDefinition::new(
            4,
            "table_name",
            4,
            KalamDataType::Text,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Table name (optional)".to_string()),
        ),
        ColumnDefinition::new(
            5,
            "status",
            5,
            KalamDataType::Text,
            false,
            false,
            false,
            ColumnDefault::None,
            Some("Job status: pending, running, completed, failed, cancelled".to_string()),
        ),
        ColumnDefinition::new(
            6,
            "parameters",
            6,
            KalamDataType::Text,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Job parameters (JSON)".to_string()),
        ),
        ColumnDefinition::new(
            7,
            "result",
            7,
            KalamDataType::Text,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Job result".to_string()),
        ),
        ColumnDefinition::new(
            8,
            "trace",
            8,
            KalamDataType::Text,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Job trace information".to_string()),
        ),
        ColumnDefinition::new(
            9,
            "memory_used",
            9,
            KalamDataType::BigInt,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Memory used in bytes".to_string()),
        ),
        ColumnDefinition::new(
            10,
            "cpu_used",
            10,
            KalamDataType::BigInt,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("CPU time used in microseconds".to_string()),
        ),
        ColumnDefinition::new(
            11,
            "created_at",
            11,
            KalamDataType::Timestamp,
            false,
            false,
            false,
            ColumnDefault::None,
            Some("Job creation timestamp".to_string()),
        ),
        ColumnDefinition::new(
            12,
            "started_at",
            12,
            KalamDataType::Timestamp,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Job start timestamp".to_string()),
        ),
        ColumnDefinition::new(
            13,
            "completed_at",
            13,
            KalamDataType::Timestamp,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Job completion timestamp".to_string()),
        ),
        ColumnDefinition::new(
            14,
            "node_id",
            14,
            KalamDataType::Text,
            false,
            false,
            false,
            ColumnDefault::None,
            Some("Node ID executing the job".to_string()),
        ),
        ColumnDefinition::new(
            15,
            "error_message",
            15,
            KalamDataType::Text,
            true,
            false,
            false,
            ColumnDefault::None,
            Some("Error message if job failed".to_string()),
        ),
    ];

    TableDefinition::new(
        NamespaceId::system(),
        TableName::new("jobs"),
        TableType::System,
        columns,
        TableOptions::system(),
        Some("Background jobs for database maintenance".to_string()),
    )
    .expect("Failed to create system.jobs table definition")
}
