/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_kalamclient_free: (a: number, b: number) => void;
export const kalamclient_new: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const kalamclient_setAutoReconnect: (a: number, b: number) => void;
export const kalamclient_setReconnectDelay: (a: number, b: bigint, c: bigint) => void;
export const kalamclient_setMaxReconnectAttempts: (a: number, b: number) => void;
export const kalamclient_getReconnectAttempts: (a: number) => number;
export const kalamclient_isReconnecting: (a: number) => number;
export const kalamclient_getLastSeqId: (a: number, b: number, c: number) => [number, number];
export const kalamclient_connect: (a: number) => any;
export const kalamclient_disconnect: (a: number) => any;
export const kalamclient_isConnected: (a: number) => number;
export const kalamclient_insert: (a: number, b: number, c: number, d: number, e: number) => any;
export const kalamclient_delete: (a: number, b: number, c: number, d: number, e: number) => any;
export const kalamclient_query: (a: number, b: number, c: number) => any;
export const kalamclient_subscribe: (a: number, b: number, c: number, d: any) => any;
export const kalamclient_subscribeWithSql: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const kalamclient_unsubscribe: (a: number, b: number, c: number) => any;
export const wasm_bindgen__convert__closures_____invoke__hbe312fe94906cca5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h07a7edbb3f89726e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h58212949185b0233: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h882e84b55e202da7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h762ee00b4618786e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h631465b85669de06: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
