/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_kalamclient_free: (a: number, b: number) => void;
export const kalamclient_anonymous: (a: number, b: number) => [number, number, number];
export const kalamclient_connect: (a: number) => any;
export const kalamclient_delete: (a: number, b: number, c: number, d: number, e: number) => any;
export const kalamclient_disconnect: (a: number) => any;
export const kalamclient_getAuthType: (a: number) => [number, number];
export const kalamclient_getLastSeqId: (a: number, b: number, c: number) => [number, number];
export const kalamclient_getReconnectAttempts: (a: number) => number;
export const kalamclient_insert: (a: number, b: number, c: number, d: number, e: number) => any;
export const kalamclient_isConnected: (a: number) => number;
export const kalamclient_isReconnecting: (a: number) => number;
export const kalamclient_new: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const kalamclient_query: (a: number, b: number, c: number) => any;
export const kalamclient_setAutoReconnect: (a: number, b: number) => void;
export const kalamclient_setMaxReconnectAttempts: (a: number, b: number) => void;
export const kalamclient_setReconnectDelay: (a: number, b: bigint, c: bigint) => void;
export const kalamclient_subscribe: (a: number, b: number, c: number, d: any) => any;
export const kalamclient_subscribeWithSql: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const kalamclient_unsubscribe: (a: number, b: number, c: number) => any;
export const kalamclient_withJwt: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__hd75e56b83013f17b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1bc171d9f47ef810: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8a410ccdbaca7a80: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4f4829089d542869: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__haaf0e2d57ce7f6f7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h14e8fa85ad019085: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
