openapi: 3.0.3
info:
  title: KalamDb API
  description: REST API for chat and AI message history storage with real-time streaming
  version: 1.0.0
  contact:
    name: KalamDb Team
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.kalamdb.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/v1/messages:
    post:
      summary: Submit a new message
      description: Store a message in the system. Returns immediately after writing to RocksDB.
      operationId: submitMessage
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              userMessage:
                summary: User message
                value:
                  conversationId: "conv_abc123"
                  from: "user_john"
                  timestamp: 1696800000000000
                  content: "Hello, how are you?"
                  metadata:
                    role: "user"
                    clientId: "web-app"
              aiResponse:
                summary: AI response
                value:
                  conversationId: "conv_abc123"
                  from: "ai_assistant"
                  timestamp: 1696800001500000
                  content: "I'm doing well, thank you!"
                  metadata:
                    role: "assistant"
                    model: "gpt-4"
                    tokens: 12
      responses:
        '201':
          description: Message accepted and stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid request (missing required fields, content too large)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized (invalid or missing JWT token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: Message content exceeds size limit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Query messages
      description: Retrieve messages with filtering and pagination. Queries both RocksDB (recent) and Parquet (historical).
      operationId: queryMessages
      tags:
        - Messages
      parameters:
        - name: userId
          in: query
          required: false
          description: Filter messages by user ID (defaults to authenticated user from JWT)
          schema:
            type: string
            example: "user_john"
        - name: conversationId
          in: query
          required: false
          description: Filter messages by conversation ID
          schema:
            type: string
            example: "conv_abc123"
        - name: sinceId
          in: query
          required: false
          description: Return messages with msgId > sinceId (for pagination or replay)
          schema:
            type: integer
            format: int64
            example: 1234567890123456
        - name: untilId
          in: query
          required: false
          description: Return messages with msgId < untilId
          schema:
            type: integer
            format: int64
            example: 1234567899999999
        - name: limit
          in: query
          required: false
          description: Maximum number of messages to return (default 50, max 1000)
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 50
            example: 50
        - name: order
          in: query
          required: false
          description: Sort order by msgId (default desc for latest first)
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/conversations:
    get:
      summary: List conversations
      description: Retrieve all conversations for a user with metadata (firstMsgId, lastMsgId, timestamps)
      operationId: listConversations
      tags:
        - Conversations
      parameters:
        - name: userId
          in: query
          required: false
          description: Filter conversations by user ID (defaults to authenticated user from JWT)
          schema:
            type: string
            example: "user_john"
      responses:
        '200':
          description: Conversations retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/conversations/{conversationId}:
    get:
      summary: Get conversation metadata
      description: Retrieve metadata for a specific conversation
      operationId: getConversation
      tags:
        - Conversations
      parameters:
        - name: conversationId
          in: path
          required: true
          description: Conversation identifier
          schema:
            type: string
            example: "conv_abc123"
      responses:
        '200':
          description: Conversation metadata retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/query:
    post:
      summary: Execute SQL query
      description: Execute arbitrary SQL query against message data using DataFusion. Admin-only endpoint.
      operationId: executeSqlQuery
      tags:
        - Query
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: SQL query string
                  example: "SELECT conversationId, COUNT(*) as msg_count FROM messages WHERE userId = 'user_john' GROUP BY conversationId"
                params:
                  type: object
                  description: Query parameters (for parameterized queries)
                  additionalProperties: true
                  example:
                    userId: "user_john"
      responses:
        '200':
          description: Query executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid SQL query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized (requires admin privileges)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/health:
    get:
      summary: Health check
      description: Check if the server is running and healthy
      operationId: healthCheck
      tags:
        - System
      security: []
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  version:
                    type: string
                    example: "1.0.0"
                  uptime:
                    type: integer
                    description: Server uptime in seconds
                    example: 86400

  /api/admin/subscriptions:
    get:
      summary: List active subscriptions
      description: Retrieve all active WebSocket subscriptions. Admin-only.
      operationId: listSubscriptions
      tags:
        - Admin
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Active subscriptions retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsResponse'
        '401':
          description: Unauthorized (requires admin privileges)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/admin/config:
    get:
      summary: Get system configuration
      description: Retrieve current system configuration. Admin-only.
      operationId: getConfig
      tags:
        - Admin
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Configuration retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update system configuration
      description: Update system configuration. Some changes require server restart. Admin-only.
      operationId: updateConfig
      tags:
        - Admin
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigUpdate'
      responses:
        '200':
          description: Configuration updated (may require restart)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  requiresRestart:
                    type: boolean
                    description: True if server restart required for changes to take effect
                    example: true
        '400':
          description: Invalid configuration values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/admin/metrics:
    get:
      summary: Get system metrics snapshot
      description: Retrieve current system metrics (storage, throughput, performance). Admin-only.
      operationId: getMetrics
      tags:
        - Admin
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Metrics retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metrics'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token with userId in 'sub' claim

  schemas:
    MessageRequest:
      type: object
      required:
        - conversationId
        - from
        - timestamp
        - content
      properties:
        conversationId:
          type: string
          description: Conversation identifier
          maxLength: 255
          example: "conv_abc123"
        from:
          type: string
          description: Sender user ID
          maxLength: 255
          example: "user_john"
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp in microseconds (UTC)
          example: 1696800000000000
        content:
          type: string
          description: Message body/text
          minLength: 1
          maxLength: 1048576
          example: "Hello, how are you?"
        metadata:
          type: object
          description: Flexible key-value metadata (JSON)
          additionalProperties: true
          example:
            role: "user"
            clientId: "web-app"

    MessageResponse:
      type: object
      properties:
        msgId:
          type: integer
          format: int64
          description: Generated snowflake ID for this message
          example: 1234567890123456
        acknowledged:
          type: boolean
          description: True if message was accepted and stored
          example: true

    Message:
      type: object
      properties:
        msgId:
          type: integer
          format: int64
          example: 1234567890123456
        conversationId:
          type: string
          example: "conv_abc123"
        from:
          type: string
          example: "user_john"
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp in microseconds (UTC)
          example: 1696800000000000
        content:
          type: string
          example: "Hello, how are you?"
        metadata:
          type: object
          additionalProperties: true
          example:
            role: "user"

    MessagesResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        hasMore:
          type: boolean
          description: True if more messages available (pagination)
          example: false
        nextCursor:
          type: integer
          format: int64
          description: msgId to use as 'sinceId' for next page
          example: 1234567890123456
          nullable: true

    Conversation:
      type: object
      properties:
        conversationId:
          type: string
          example: "conv_abc123"
        firstMsgId:
          type: integer
          format: int64
          example: 1234567890000000
        lastMsgId:
          type: integer
          format: int64
          example: 1234567899999999
        created:
          type: integer
          format: int64
          description: Unix timestamp in microseconds
          example: 1696800000000000
        updated:
          type: integer
          format: int64
          description: Unix timestamp in microseconds
          example: 1696850000000000

    ConversationsResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/Conversation'

    QueryResponse:
      type: object
      properties:
        columns:
          type: array
          description: Column names
          items:
            type: string
          example: ["conversationId", "msg_count"]
        rows:
          type: array
          description: Query result rows
          items:
            type: array
            items: {}
          example:
            - ["conv_abc123", 150]
            - ["conv_xyz789", 75]
        executionTimeMs:
          type: integer
          description: Query execution time in milliseconds
          example: 245

    SubscriptionsResponse:
      type: object
      properties:
        subscriptions:
          type: array
          items:
            type: object
            properties:
              connectionId:
                type: string
                format: uuid
                example: "550e8400-e29b-41d4-a716-446655440000"
              userId:
                type: string
                example: "user_john"
              conversationId:
                type: string
                nullable: true
                example: "conv_abc123"
              lastMsgId:
                type: integer
                format: int64
                nullable: true
                example: 1234567890123456
              connectedAt:
                type: integer
                format: int64
                description: Unix timestamp in microseconds
                example: 1696800000000000
              lastHeartbeat:
                type: integer
                format: int64
                description: Unix timestamp in microseconds
                example: 1696850000000000

    Config:
      type: object
      properties:
        messageSizeLimitBytes:
          type: integer
          description: Maximum message content size in bytes
          example: 1048576
        consolidationIntervalSeconds:
          type: integer
          description: Time interval between consolidation cycles
          example: 300
        consolidationMessageThreshold:
          type: integer
          description: Message count threshold for consolidation
          example: 10000
        storageBackend:
          type: string
          enum: [local, s3]
          example: "local"
        storageConfig:
          type: object
          description: Backend-specific storage configuration
          additionalProperties: true

    ConfigUpdate:
      type: object
      properties:
        messageSizeLimitBytes:
          type: integer
          example: 2097152
        consolidationIntervalSeconds:
          type: integer
          example: 600
        consolidationMessageThreshold:
          type: integer
          example: 20000

    Metrics:
      type: object
      properties:
        storage:
          type: object
          properties:
            totalMessages:
              type: integer
              format: int64
              example: 1000000
            sizeBytes:
              type: integer
              format: int64
              example: 500000000
            userCount:
              type: integer
              example: 1000
        throughput:
          type: object
          properties:
            messagesPerSecond:
              type: number
              format: float
              example: 150.5
            queriesPerSecond:
              type: number
              format: float
              example: 10.2
        subscriptions:
          type: object
          properties:
            activeConnections:
              type: integer
              example: 500
        performance:
          type: object
          properties:
            cpuPercent:
              type: number
              format: float
              example: 45.2
            memoryMB:
              type: integer
              example: 2048
            diskIOPS:
              type: integer
              example: 100

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid request: missing required field 'conversationId'"
        code:
          type: string
          description: Error code for programmatic handling
          example: "MISSING_FIELD"
