openapi: 3.0.3
info:
  title: KalamDB SQL API
  description: |
    SQL-first REST API for chat and AI message history storage.
    
    **Core Philosophy**: Single SQL query endpoint for all data operations.
    All CRUD operations (messages, conversations, users) use SQL queries.
    
    **Authentication**: JWT token enforces userId scope.
    Users can only query their own data (`userId.messages`, `userId.conversations`).
    Admin users can query across all users with special permissions.
    
  version: 2.0.0
  contact:
    name: KalamDB Team

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.kalamdb.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/v1/query:
    post:
      summary: Execute SQL query
      description: |
        Universal SQL query endpoint for all data operations.
        
        **Supported Tables**:
        - `userId.messages` - All messages for this user
        - `userId.conversations` - All conversations for this user
        - `userId.conversationUsers` - Group conversation memberships
        
        **Query Execution**:
        1. Parse SQL and validate syntax
        2. Extract userId from JWT token
        3. Validate userId scope matches table prefix
        4. Execute query across RocksDB (hot) + Parquet (cold)
        5. Merge results and return JSON
        
        **Performance**:
        - Hot data (RocksDB): <10ms
        - Cold data (Parquet): 50-200ms depending on size
        - Automatic caching for repeated queries
        
      operationId: executeQuery
      tags:
        - Query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
            examples:
              queryMessages:
                summary: Query messages in a conversation
                value:
                  sql: "SELECT * FROM userId.messages WHERE conversationId = 'conv_123' ORDER BY timestamp DESC LIMIT 100"
              queryConversations:
                summary: List all conversations
                value:
                  sql: "SELECT * FROM userId.conversations ORDER BY updated DESC"
              aggregateMessages:
                summary: Count messages per conversation
                value:
                  sql: "SELECT conversationId, COUNT(*) as msgCount FROM userId.messages GROUP BY conversationId"
              searchMessages:
                summary: Full-text search in messages
                value:
                  sql: "SELECT * FROM userId.messages WHERE content LIKE '%search term%' LIMIT 50"
              deleteMessage:
                summary: Delete a single message
                value:
                  sql: "DELETE FROM userId.messages WHERE msgId = 123456789"
              deleteConversation:
                summary: Delete entire conversation
                value:
                  sql: "DELETE FROM userId.conversations WHERE conversationId = 'conv_123'"
              insertConversation:
                summary: Create new conversation
                value:
                  sql: "INSERT INTO userId.conversations (conversationId, conversationType, userId, firstMsgId, lastMsgId, created, updated, storagePath) VALUES ('conv_new', 'ai', 'user_john', 1, 1, 1699000000, 1699000000, 'user_john/')"
              updateConversation:
                summary: Update conversation metadata
                value:
                  sql: "UPDATE userId.conversations SET lastMsgId = 999, updated = 1699999999 WHERE conversationId = 'conv_123'"
      responses:
        '200':
          description: Query executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
              examples:
                selectMessages:
                  summary: SELECT query result
                  value:
                    columns: ["msgId", "conversationId", "from", "timestamp", "content", "metadata"]
                    rows:
                      - [123, "conv_123", "user_john", 1699000000, "Hello", "{}"]
                      - [124, "conv_123", "ai", 1699000001, "Hi there!", "{}"]
                    rowCount: 2
                    executionTimeMs: 15
                deleteResult:
                  summary: DELETE query result
                  value:
                    rowsAffected: 1
                    executionTimeMs: 8
                insertResult:
                  summary: INSERT query result
                  value:
                    rowsAffected: 1
                    executionTimeMs: 5
        '400':
          description: Invalid SQL query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                syntaxError:
                  value:
                    error: "SQL syntax error"
                    message: "Expected SELECT, INSERT, UPDATE, or DELETE at position 0"
                scopeViolation:
                  value:
                    error: "Scope violation"
                    message: "User user_john cannot access user_alice.messages"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/messages:
    post:
      summary: Submit a new message (legacy/convenience endpoint)
      description: |
        **Optional convenience endpoint** for submitting messages.
        
        Internally translates to SQL INSERT but provides:
        - Automatic msgId generation (snowflake ID)
        - Timestamp defaulting
        - Content validation
        - Parallel writes to all participants (group conversations)
        
        For flexibility, prefer using `/api/v1/query` with SQL INSERT.
      operationId: submitMessage
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              textMessage:
                value:
                  conversationId: "conv_123"
                  conversationType: "ai"
                  from: "user_john"
                  content: "Hello AI"
                  metadata:
                    role: "user"
              messageWithMedia:
                value:
                  conversationId: "conv_456"
                  conversationType: "group"
                  from: "user_alice"
                  content: "Check out this image!"
                  contentRef: "shared/conversations/conv_456/media-789.jpg"
                  metadata:
                    mediaType: "image/jpeg"
                    width: 1920
                    height: 1080
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/media/upload:
    post:
      summary: Upload media file
      description: |
        Upload media file (image, document, audio, video) for a conversation.
        
        **Storage Logic**:
        - AI conversation: stored in `{userId}/media-{msgId}.{ext}`
        - Group conversation: stored in `shared/conversations/{convId}/media-{msgId}.{ext}`
        
        Returns `contentRef` to use in message submission.
      operationId: uploadMedia
      tags:
        - Media
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - conversationId
                - conversationType
              properties:
                file:
                  type: string
                  format: binary
                  description: Media file to upload
                conversationId:
                  type: string
                  description: Conversation this media belongs to
                conversationType:
                  type: string
                  enum: [ai, group]
                  description: Type of conversation (determines storage location)
      responses:
        '201':
          description: Media uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaUploadResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/health:
    get:
      summary: Health check
      description: Check if the server is running and healthy
      operationId: healthCheck
      tags:
        - System
      security: []
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  version:
                    type: string
                    example: "1.0.0"
                  uptime:
                    type: integer
                    description: Server uptime in seconds

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token with claims:
        - `userId`: User identifier (required)
        - `role`: User role (user, admin)
        - `exp`: Expiration timestamp

  schemas:
    QueryRequest:
      type: object
      required:
        - sql
      properties:
        sql:
          type: string
          description: SQL query to execute
          example: "SELECT * FROM userId.messages WHERE conversationId = 'conv_123' LIMIT 100"
        parameters:
          type: object
          description: Optional query parameters (for prepared statements)
          additionalProperties: true
          example:
            conversationId: "conv_123"
            limit: 100

    QueryResponse:
      type: object
      properties:
        columns:
          type: array
          items:
            type: string
          description: Column names in result set
          example: ["msgId", "conversationId", "from", "timestamp", "content"]
        rows:
          type: array
          items:
            type: array
            items: {}
          description: Result rows (array of arrays)
          example:
            - [123, "conv_123", "user_john", 1699000000, "Hello"]
            - [124, "conv_123", "ai", 1699000001, "Hi!"]
        rowCount:
          type: integer
          description: Number of rows returned
          example: 2
        rowsAffected:
          type: integer
          description: Number of rows affected (for INSERT/UPDATE/DELETE)
          example: 1
        executionTimeMs:
          type: integer
          description: Query execution time in milliseconds
          example: 15

    MessageRequest:
      type: object
      required:
        - conversationId
        - conversationType
        - from
        - content
      properties:
        conversationId:
          type: string
          description: Conversation identifier
          example: "conv_abc123"
        conversationType:
          type: string
          enum: [ai, group]
          description: Type of conversation
          example: "ai"
        from:
          type: string
          description: Sender identifier (userId or "ai")
          example: "user_john"
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp in microseconds (optional, auto-generated if not provided)
          example: 1696800000000000
        content:
          type: string
          description: Message content (text or preview for large/media messages)
          maxLength: 1048576
          example: "Hello, how are you?"
        contentRef:
          type: string
          description: Reference to large content or media file (optional)
          example: "shared/conversations/conv_123/msg-456.bin"
        metadata:
          type: object
          description: Flexible key-value metadata
          additionalProperties: true
          example:
            role: "user"
            clientId: "web-app"

    MessageResponse:
      type: object
      properties:
        msgId:
          type: integer
          format: int64
          description: Generated message ID (snowflake)
          example: 1234567890123456
        conversationId:
          type: string
          example: "conv_abc123"
        timestamp:
          type: integer
          format: int64
          example: 1696800000000000
        status:
          type: string
          enum: [buffered, consolidated]
          description: Storage status
          example: "buffered"

    MediaUploadResponse:
      type: object
      properties:
        contentRef:
          type: string
          description: Reference path to uploaded media
          example: "shared/conversations/conv_123/media-789.jpg"
        metadata:
          type: object
          description: Extracted media metadata
          properties:
            mediaType:
              type: string
              example: "image/jpeg"
            fileSize:
              type: integer
              example: 245760
            width:
              type: integer
              example: 1920
            height:
              type: integer
              example: 1080
            thumbnailRef:
              type: string
              example: "shared/conversations/conv_123/media-789-thumb.jpg"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
          example: "ValidationError"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid SQL syntax"
        details:
          type: object
          description: Additional error details
          additionalProperties: true

  responses:
    UnauthorizedError:
      description: Authentication required or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Unauthorized"
            message: "Invalid or missing JWT token"

    BadRequestError:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "BadRequest"
            message: "Missing required field: conversationId"

tags:
  - name: Query
    description: SQL query operations (primary interface)
  - name: Messages
    description: Message operations (convenience endpoints)
  - name: Media
    description: Media file upload
  - name: System
    description: System health and status
