// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { getKalamTableConfig, kSystemColumns, kTable } from '@kalamdb/orm';
import { text, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const chat_demo_agent_events = kTable.stream("chat_demo.agent_events", {
  ...kSystemColumns(["_seq"] as const),
  id: text("id").default(sql``).primaryKey(),
  response_id: text("response_id").notNull(),
  room: text("room").default(sql``).notNull(),
  sender_username: text("sender_username").notNull(),
  stage: text("stage").notNull(),
  preview: text("preview").default(sql``).notNull(),
  message: text("message").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const chat_demo_agent_eventsConfig = getKalamTableConfig(chat_demo_agent_events)!;
export type ChatDemoAgentEvents = typeof chat_demo_agent_events.$inferSelect;
export type NewChatDemoAgentEvents = typeof chat_demo_agent_events.$inferInsert;

export const chat_demo_messages = kTable.user("chat_demo.messages", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: text("id").default(sql``).primaryKey(),
  room: text("room").default(sql``).notNull(),
  role: text("role").notNull(),
  author: text("author").notNull(),
  sender_username: text("sender_username").notNull(),
  content: text("content").notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const chat_demo_messagesConfig = getKalamTableConfig(chat_demo_messages)!;
export type ChatDemoMessages = typeof chat_demo_messages.$inferSelect;
export type NewChatDemoMessages = typeof chat_demo_messages.$inferInsert;
