# KalamDB Local Cluster Management Script (No Docker) - Windows PowerShell
#
# This script runs a 3-node KalamDB cluster locally without Docker.
# Each node runs as a separate process with its own data directory.
#
# Usage:
#   .\scripts\cluster-local.ps1 start    - Start the 3-node cluster
#   .\scripts\cluster-local.ps1 stop     - Stop all nodes
#   .\scripts\cluster-local.ps1 restart  - Restart the cluster
#   .\scripts\cluster-local.ps1 status   - Check cluster status
#   .\scripts\cluster-local.ps1 logs 1   - View logs from node 1, 2, or 3
#   .\scripts\cluster-local.ps1 clean    - Stop and remove all data
#   .\scripts\cluster-local.ps1 build    - Build the server binary
#
# Prerequisites:
#   - Rust toolchain installed (cargo, rustc)
#   - Ports 8081-8083 available (HTTP)
#   - Ports 9081-9083 available (Raft RPC)

param(
    [Parameter(Position=0)]
    [ValidateSet("start", "stop", "restart", "status", "logs", "clean", "build", "help")]
    [string]$Command = "help",
    
    [Parameter(Position=1)]
    [int]$NodeId = 0
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$ClusterDataDir = Join-Path $ProjectRoot ".cluster-local"

# Node configuration
$Nodes = @(
    @{ Id = 1; HttpPort = 8081; RpcPort = 9081 },
    @{ Id = 2; HttpPort = 8082; RpcPort = 9082 },
    @{ Id = 3; HttpPort = 8083; RpcPort = 9083 }
)

function Write-Header {
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════════════════════════════╗" -ForegroundColor Blue
    Write-Host "║        KalamDB Local Cluster (No Docker) - Windows                ║" -ForegroundColor Blue
    Write-Host "╚═══════════════════════════════════════════════════════════════════╝" -ForegroundColor Blue
    Write-Host ""
}

function Test-Cargo {
    if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
        Write-Host "Error: Cargo is not installed" -ForegroundColor Red
        Write-Host "Please install Rust: https://rustup.rs/"
        exit 1
    }
}

function Build-Server {
    Write-Header
    Write-Host "Building KalamDB server..." -ForegroundColor Yellow
    
    Push-Location (Join-Path $ProjectRoot "backend")
    try {
        cargo build --release
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✓ Server built successfully" -ForegroundColor Green
        } else {
            Write-Host "✗ Build failed" -ForegroundColor Red
            exit 1
        }
    } finally {
        Pop-Location
    }
}

function New-NodeConfig {
    param([int]$NodeId, [int]$HttpPort, [int]$RpcPort)
    
    $DataDir = Join-Path $ClusterDataDir "node$NodeId"
    $ConfigFile = Join-Path $DataDir "server.toml"
    
    # Create directories
    New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $DataDir "data") | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $DataDir "logs") | Out-Null
    
    # Build peers list
    $Peers = $Nodes | Where-Object { $_.Id -ne $NodeId } | ForEach-Object { "`"127.0.0.1:$($_.RpcPort)`"" }
    $PeersStr = $Peers -join ", "
    
    $Config = @"
# KalamDB Node $NodeId Configuration
# Auto-generated by cluster-local.ps1

[server]
host = "127.0.0.1"
port = $HttpPort
data_path = "$($DataDir -replace '\\', '/')/data"
storage_path = "$($DataDir -replace '\\', '/')/data/storage"

[logging]
level = "info"
format = "json"
file = "$($DataDir -replace '\\', '/')/logs/server.jsonl"

[cluster]
enabled = true
cluster_id = "kalamdb-local-cluster"
node_id = $NodeId
rpc_host = "127.0.0.1"
rpc_port = $RpcPort
peers = [$PeersStr]
heartbeat_interval_ms = 150
election_timeout_min_ms = 300
election_timeout_max_ms = 500

[auth]
enabled = true
root_password = "kalamdb123"
jwt_secret = "local-cluster-jwt-secret-key-for-testing-only"
jwt_expiry_hours = 24
"@
    
    Set-Content -Path $ConfigFile -Value $Config
    return $ConfigFile
}

function Start-Node {
    param([int]$NodeId, [int]$HttpPort, [int]$RpcPort)
    
    Write-Host "Starting node $NodeId..." -ForegroundColor Yellow
    
    $ConfigFile = New-NodeConfig -NodeId $NodeId -HttpPort $HttpPort -RpcPort $RpcPort
    $DataDir = Join-Path $ClusterDataDir "node$NodeId"
    $PidFile = Join-Path $DataDir "server.pid"
    $LogFile = Join-Path $DataDir "logs" "stdout.log"
    
    # Check if already running
    if (Test-Path $PidFile) {
        $OldPid = Get-Content $PidFile
        try {
            $Process = Get-Process -Id $OldPid -ErrorAction SilentlyContinue
            if ($Process) {
                Write-Host "  Node $NodeId already running (PID: $OldPid)" -ForegroundColor Yellow
                return
            }
        } catch {}
        Remove-Item $PidFile -Force
    }
    
    # Find binary
    $Binary = Join-Path $ProjectRoot "target\release\kalamdb-server.exe"
    if (-not (Test-Path $Binary)) {
        $Binary = Join-Path $ProjectRoot "target\debug\kalamdb-server.exe"
    }
    if (-not (Test-Path $Binary)) {
        Write-Host "  Server binary not found. Run '.\scripts\cluster-local.ps1 build' first." -ForegroundColor Red
        exit 1
    }
    
    # Start the server
    $env:KALAMDB_CONFIG = $ConfigFile
    $Process = Start-Process -FilePath $Binary -WindowStyle Hidden -PassThru -RedirectStandardOutput $LogFile -RedirectStandardError "$LogFile.err"
    Set-Content -Path $PidFile -Value $Process.Id
    
    Start-Sleep -Seconds 2
    
    if (-not $Process.HasExited) {
        Write-Host "  ✓ Node $NodeId started (PID: $($Process.Id), HTTP: $HttpPort, RPC: $RpcPort)" -ForegroundColor Green
    } else {
        Write-Host "  ✗ Node $NodeId failed to start. Check $LogFile" -ForegroundColor Red
    }
}

function Stop-Node {
    param([int]$NodeId)
    
    $DataDir = Join-Path $ClusterDataDir "node$NodeId"
    $PidFile = Join-Path $DataDir "server.pid"
    
    if (Test-Path $PidFile) {
        $Pid = Get-Content $PidFile
        try {
            $Process = Get-Process -Id $Pid -ErrorAction SilentlyContinue
            if ($Process) {
                Write-Host "Stopping node $NodeId (PID: $Pid)..." -ForegroundColor Yellow
                Stop-Process -Id $Pid -Force -ErrorAction SilentlyContinue
                Start-Sleep -Seconds 1
            }
        } catch {}
        Remove-Item $PidFile -Force
        Write-Host "  ✓ Node $NodeId stopped" -ForegroundColor Green
    } else {
        Write-Host "  Node $NodeId not running" -ForegroundColor Yellow
    }
}

function Test-NodeHealth {
    param([int]$HttpPort)
    
    try {
        $Response = Invoke-WebRequest -Uri "http://127.0.0.1:$HttpPort/v1/api/healthcheck" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
        return $Response.StatusCode -eq 200
    } catch {
        return $false
    }
}

function Start-Cluster {
    Write-Header
    Write-Host "Starting 3-node local cluster..." -ForegroundColor Green
    Write-Host ""
    
    # Check if binary exists
    $Binary = Join-Path $ProjectRoot "target\release\kalamdb-server.exe"
    if (-not (Test-Path $Binary)) {
        $Binary = Join-Path $ProjectRoot "target\debug\kalamdb-server.exe"
    }
    if (-not (Test-Path $Binary)) {
        Write-Host "Server binary not found. Building..." -ForegroundColor Yellow
        Build-Server
    }
    
    # Create data directory
    New-Item -ItemType Directory -Force -Path $ClusterDataDir | Out-Null
    
    # Start all nodes
    foreach ($Node in $Nodes) {
        Start-Node -NodeId $Node.Id -HttpPort $Node.HttpPort -RpcPort $Node.RpcPort
    }
    
    Write-Host ""
    Write-Host "Waiting for cluster to initialize..." -ForegroundColor Yellow
    
    # Wait for all nodes to be healthy
    $Healthy = $false
    for ($i = 1; $i -le 30; $i++) {
        $Count = 0
        foreach ($Node in $Nodes) {
            if (Test-NodeHealth -HttpPort $Node.HttpPort) { $Count++ }
        }
        if ($Count -eq 3) {
            $Healthy = $true
            break
        }
        Start-Sleep -Seconds 1
    }
    
    Write-Host ""
    if ($Healthy) {
        Write-Host "╔═══════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
        Write-Host "║                    Cluster Ready!                                 ║" -ForegroundColor Green
        Write-Host "╚═══════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
        Write-Host ""
        Write-Host "Node 1: http://127.0.0.1:8081"
        Write-Host "Node 2: http://127.0.0.1:8082"
        Write-Host "Node 3: http://127.0.0.1:8083"
        Write-Host ""
        Write-Host "Root password: kalamdb123"
        Write-Host ""
        Write-Host "Connect with CLI:"
        Write-Host "  kalam --server http://127.0.0.1:8081 --username root --password kalamdb123"
        Write-Host ""
        Write-Host "Run cluster tests:"
        Write-Host "  cd cli; cargo test --test cluster"
    } else {
        Write-Host "Cluster failed to initialize. Check logs:" -ForegroundColor Red
        Write-Host "  $ClusterDataDir\node1\logs\stdout.log"
        Write-Host "  $ClusterDataDir\node2\logs\stdout.log"
        Write-Host "  $ClusterDataDir\node3\logs\stdout.log"
        exit 1
    }
}

function Stop-Cluster {
    Write-Header
    Write-Host "Stopping cluster..." -ForegroundColor Yellow
    Write-Host ""
    
    foreach ($Node in $Nodes) {
        Stop-Node -NodeId $Node.Id
    }
    
    Write-Host ""
    Write-Host "Cluster stopped." -ForegroundColor Green
}

function Show-Status {
    Write-Header
    Write-Host "Cluster Status:" -ForegroundColor Blue
    Write-Host ""
    
    foreach ($Node in $Nodes) {
        $DataDir = Join-Path $ClusterDataDir "node$($Node.Id)"
        $PidFile = Join-Path $DataDir "server.pid"
        
        Write-Host -NoNewline "  Node $($Node.Id): "
        
        if (Test-Path $PidFile) {
            $Pid = Get-Content $PidFile
            try {
                $Process = Get-Process -Id $Pid -ErrorAction SilentlyContinue
                if ($Process) {
                    if (Test-NodeHealth -HttpPort $Node.HttpPort) {
                        Write-Host "Running (PID: $Pid, healthy)" -ForegroundColor Green
                    } else {
                        Write-Host "Running (PID: $Pid, not healthy yet)" -ForegroundColor Yellow
                    }
                } else {
                    Write-Host "Dead (stale PID file)" -ForegroundColor Red
                }
            } catch {
                Write-Host "Dead (stale PID file)" -ForegroundColor Red
            }
        } else {
            Write-Host "Not running" -ForegroundColor Red
        }
    }
    Write-Host ""
}

function Show-Logs {
    param([int]$NodeId)
    
    $LogFile = Join-Path $ClusterDataDir "node$NodeId" "logs" "stdout.log"
    
    if (Test-Path $LogFile) {
        Write-Host "=== Node $NodeId Logs ===" -ForegroundColor Blue
        Get-Content -Tail 100 $LogFile
    } else {
        Write-Host "No log file found for node $NodeId" -ForegroundColor Red
    }
}

function Clear-Cluster {
    Write-Header
    Write-Host "Cleaning up cluster data..." -ForegroundColor Yellow
    
    Stop-Cluster
    
    if (Test-Path $ClusterDataDir) {
        Remove-Item -Recurse -Force $ClusterDataDir
        Write-Host "✓ Removed $ClusterDataDir" -ForegroundColor Green
    }
    
    Write-Host "Cleanup complete." -ForegroundColor Green
}

# Main command handler
switch ($Command) {
    "start" { Start-Cluster }
    "stop" { Stop-Cluster }
    "restart" { 
        Stop-Cluster
        Start-Sleep -Seconds 2
        Start-Cluster
    }
    "status" { Show-Status }
    "logs" {
        if ($NodeId -lt 1 -or $NodeId -gt 3) {
            Write-Host "Usage: .\cluster-local.ps1 logs <node_number>"
            Write-Host "  node_number: 1, 2, or 3"
            exit 1
        }
        Show-Logs -NodeId $NodeId
    }
    "clean" { Clear-Cluster }
    "build" { Build-Server }
    default {
        Write-Host "KalamDB Local Cluster Script"
        Write-Host ""
        Write-Host "Usage: .\cluster-local.ps1 <command>"
        Write-Host ""
        Write-Host "Commands:"
        Write-Host "  start     Start the 3-node cluster"
        Write-Host "  stop      Stop all nodes"
        Write-Host "  restart   Restart the cluster"
        Write-Host "  status    Show cluster status"
        Write-Host "  logs N    Show logs for node N (1, 2, or 3)"
        Write-Host "  clean     Stop cluster and remove all data"
        Write-Host "  build     Build the server binary"
        Write-Host ""
    }
}
